### ISSUE TITLE
kube-state-metrics - invalid metric type "info"

### ISSUE THREAD

**Issue by sebastiangaiser** [fluxcd/flux2-monitoring-example#31]
Hey, 

we upgraded [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) to v2.11.0. Since then we get the error message `invalid metric type "info"` for scraping kube-state-metrics.
With [v2.10.1](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.10.1) everything was working fine.

We already discovered that https://github.com/fluxcd/flux2-monitoring-example/issues/14 shows a similar problem but as written it was working for us in the prio version.

Additionally we found: `Info metrics are used to expose textual information which SHOULD NOT change during process lifetime. Common examples are an application's version, revision control commit, and the version of a compiler.` [source](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md#info)

**Comment by okaufmann** [comment]
I'm experiencing the same problem upgrading kube-prometheus-stack to 57.2.0 which will obviously upgrade [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) to the corresponding version.

**Comment by ansarhun** [comment]
Most likely related to: https://github.com/kubernetes/kube-state-metrics/issues/1973#issuecomment-2024736652
The fix seems to be merged: https://github.com/kubernetes/kube-state-metrics/pull/2270

**Comment by sebastiangaiser** [comment]
Upgrading kube-state-metrics to '2.12.0' solves this issue.
