### ISSUE TITLE
Version issue while monitoring FluxCD

### ISSUE THREAD

**Issue by utsavv27** [fluxcd/flux2-monitoring-example#38]
I am trying to monitor fluxcd with (https://github.com/fluxcd/flux2-monitoring-example) this repo. and while following this simple steps provided by flux but somehow I am stuck with this error while I also checked the versions of flux and k8s cluster 

Steps:
so my steps are like I forked this repo into my personal account and then I  followed the given steps as provided , after I run the bootstrap command it only install's the monitoring namespace and it's will not install any charts so when I checked it why it's not making any chart in my k9s terminal I have seen below error.

i have attached SS of Kustomizations with error below.
![image](https://github.com/fluxcd/flux2-monitoring-example/assets/156082357/2b771d3c-edc3-43aa-b5e6-04289c6fb374)
![image](https://github.com/fluxcd/flux2-monitoring-example/assets/156082357/f9311c59-f33a-4201-8d7f-4822815cd554)
![image](https://github.com/fluxcd/flux2-monitoring-example/assets/156082357/651bd6cd-9dd3-4712-a75c-4f9a9df54f9b)

**Comment by stefanprodan** [comment]
You need to bootstrap with Flux v2.3.0

**Comment by utsavv27** [comment]
i am using that latest version

**Comment by utsavv27** [comment]
so while doing flux install or bootstrap I am getting version 2.2 so can you tell me how to bootstrap with with version 2.3?
@stefanprodan

**Comment by utsavv27** [comment]
can you provide sol. to monitor with older versions? like v2.2.0 cause I have much data and I can not afford to lose it when do install and uninstall from versions
@stefanprodan

**Comment by DerRockWolf** [comment]
> can you provide sol. to monitor with older versions? like v2.2.0 cause I have much data and I can not afford to lose it when do install and uninstall from versions @stefanprodan

Just update, no need to first uninstall.
Alternatively you could also change the APIVersions in your fork to the old ones.

**Comment by mjtrangoni** [comment]
@stefanprodan what about refloating the [flux-mixin](https://github.com/fluxcd-community/flux-mixin)? This way one could also manage the flux versions with the corresponding flux APIs.

**Comment by utsavv27** [comment]
so I have installed v2.3.0 but somehow I am getting errors in charts that only Loki is installing in my system not Prometheus it shows error like below,
@stefanprodan 
![image](https://github.com/fluxcd/flux2-monitoring-example/assets/156082357/a7bebb34-714c-4817-b136-613847fb3cb7)
![image](https://github.com/fluxcd/flux2-monitoring-example/assets/156082357/62b91baa-75cb-4c41-84cc-1dc3e833b675)

**Comment by DerRockWolf** [comment]
> so I have installed v2.3.0 but somehow I am getting errors in charts that only Loki is installing in my system not Prometheus it shows error like below

I don't want to sound rude, but you should probably get a bit more familiar with how flux & kubernetes works.

The thing you are seeing isn't the an actual error, this just indicates that the source (in this case a HelmChart) is not yet ready.
